### ISSUE TITLE
Empty Custom Label Source 

### ISSUE THREAD

**Issue by ItzJChan** [nbendall34/TwitterDeviceHandleChanger#1]
Seems like the developer portal on Twitter has altered its interface, attempting to submit a Tweet with the script will successfully submit the tweet but with an empty custom label source.

**Comment by nbendall34** [comment]
I will have a look into this. could you link the tweet if it is publishing?

**Comment by ChrisSlS** [comment]
The same problem here.

I'm not sure but I think we need to enable 3rd party authentication, so the code needs to be reviewed.

**Comment by nbendall34** [comment]
So has this been resolved by the Twitter devs?

**Comment by ChrisSlS** [comment]
No, it's independent of them from what we can understand. It takes a while for the app to propagate through their system.

I don't know if that has a connection, but I do know he's working on the new API, which is behind schedule following the latest Twitter hack.

At the moment, it's been 24 hours since my app was created and the label is not yet showing on my tweet. I will inform as soon as it is good.

**Comment by ChrisSlS** [comment]
Finally, I followed the instructions from this site and it worked:

https://techwiser.com/how-to-change-the-twitter-source-label/

Does not work for project apps but works well for standalone apps...
